# PANNs acoustic-event extraction — TAU 6000 development subset

This notebook preserves the **same PANNs extraction procedure as the original
12,291-recording notebook**, but applies it only to the fixed 6000-recording
development manifest.

Preserved settings:
- PANNs `AudioTagging` / Cnn14 via `panns_inference`
- 32 kHz mono audio
- 3-second chunks
- Top-8 AudioSet events per chunk
- recording-level aggregation by `max_score`, `mean_score`, and `count`
- `num_chunks` saved so persistence can be computed as `count / num_chunks`
- checkpoint every 25 recordings

In [1]:
from pathlib import Path
import sys
import time
import json
import numpy as np
import pandas as pd
import librosa
import torch
from IPython.display import display
from panns_inference import AudioTagging, labels
print('Python:', sys.executable)
print('PyTorch:', torch.__version__)
print('CUDA:', torch.version.cuda)
print('CUDA available:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))

Python: C:\Users\22313906t\AppData\Local\anaconda3\envs\tau_env\python.exe
PyTorch: 2.13.0+cu126
CUDA: 12.6
CUDA available: True
GPU: NVIDIA RTX 2000 Ada Generation Laptop GPU

## 1. Paths

In [2]:
PROJECT_ROOT = Path('C:\\Users\\22313906t\\Desktop\\TAU_project')
DATA_DIR = PROJECT_ROOT / 'data_subset_6000'
MANIFEST_PATH = PROJECT_ROOT / 'manifests' / 'tau_balanced_6000_experiment_manifest.csv'
PANNS_RESULTS_DIR = PROJECT_ROOT / 'results_PANNs_6000'
PANNS_RESULTS_DIR.mkdir(parents=True, exist_ok=True)
ALL_EVENTS_PATH = PANNS_RESULTS_DIR / 'tau_6000_panns_events.csv'
ALL_TOP_PATH = PANNS_RESULTS_DIR / 'tau_6000_panns_top_events.csv'
ALL_ERRORS_PATH = PANNS_RESULTS_DIR / 'tau_6000_panns_errors.csv'
CONFIG_PATH = PANNS_RESULTS_DIR / 'tau_6000_panns_config.json'
print('Project:', PROJECT_ROOT)
print('Data:', DATA_DIR)
print('Manifest:', MANIFEST_PATH)
print('PANNs results:', PANNS_RESULTS_DIR)

Project: C:\Users\22313906t\Desktop\TAU_project
Data: C:\Users\22313906t\Desktop\TAU_project\data_subset_6000
Manifest: C:\Users\22313906t\Desktop\TAU_project\manifests\tau_balanced_6000_experiment_manifest.csv
PANNs results: C:\Users\22313906t\Desktop\TAU_project\results_PANNs_6000

## 2. Fixed PANNs settings

In [3]:
PANNS_SR = 32000
CHUNK_SECONDS = 3.0
TOP_K = 8
CHECKPOINT_EVERY = 25
PANNS_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
config = {
    'audio_model': 'PANNs Cnn14',
    'package': 'panns-inference',
    'sample_rate': PANNS_SR,
    'chunk_seconds': CHUNK_SECONDS,
    'top_k_per_chunk': TOP_K,
    'device': PANNS_DEVICE,
    'subset': 'TAU balanced development 6000',
}
with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
    json.dump(config, f, indent=2)
print('PANNs device:', PANNS_DEVICE)
print('PANNs sample rate:', PANNS_SR)
print('Chunk seconds:', CHUNK_SECONDS)
print('Top K per chunk:', TOP_K)

PANNs device: cuda
PANNs sample rate: 32000
Chunk seconds: 3.0
Top K per chunk: 8

## 3. Load the exact 6000-recording manifest

The original notebook scanned the complete 12,291-WAV collection.  
For the reproducibility rerun, the manifest is authoritative: only these 6000
development recordings are processed.

In [4]:
manifest_df = pd.read_csv(MANIFEST_PATH)
manifest_df['clip_id'] = manifest_df['clip_id'].astype(str)
manifest_df['ground_truth'] = manifest_df['ground_truth'].astype(str)
print('Manifest rows:', len(manifest_df))
print('Unique clip IDs:', manifest_df['clip_id'].nunique())
display(manifest_df['ground_truth'].value_counts().to_frame('number_of_clips'))
display(manifest_df.head())

Manifest rows: 6000
Unique clip IDs: 6000

                   number_of_clips
ground_truth
metro                          600
shopping mall                  600
airport                        600
metro station                  600
street traffic                 600
bus                            600
park                           600
public square                  600
tram                           600
pedestrian street              600

,clip_id,ground_truth,audio_path,video_path
0,metro-lisbon-1055-41182,metro,C:\Users\22313906t\Desktop\TAU_project\data_su...,C:\Users\22313906t\Desktop\TAU_project\data_su...
1,shopping_mall-barcelona-125-3702,shopping mall,C:\Users\22313906t\Desktop\TAU_project\data_su...,C:\Users\22313906t\Desktop\TAU_project\data_su...
2,airport-lisbon-1122-41270,airport,C:\Users\22313906t\Desktop\TAU_project\data_su...,C:\Users\22313906t\Desktop\TAU_project\data_su...
3,metro_station-stockholm-239-7087,metro station,C:\Users\22313906t\Desktop\TAU_project\data_su...,C:\Users\22313906t\Desktop\TAU_project\data_su...
4,street_traffic-prague-1193-44472,street traffic,C:\Users\22313906t\Desktop\TAU_project\data_su...,C:\Users\22313906t\Desktop\TAU_project\data_su...

## 4. Resolve audio paths

In [5]:
wav_index = None


def build_wav_index():
    wav_files = sorted((p for p in DATA_DIR.rglob('*.wav') if p.is_file()))
    index = {}
    for p in wav_files:
        index.setdefault(p.stem, []).append(p)
    print('WAV files indexed:', len(wav_files))
    return index


def resolve_audio_path(row):
    global wav_index
    if 'audio_path' in manifest_df.columns and pd.notna(row.get('audio_path')):
        candidate = Path(str(row['audio_path']))
        if candidate.exists():
            return candidate
    if wav_index is None:
        wav_index = build_wav_index()
    key = Path(str(row['clip_id'])).stem
    matches = wav_index.get(key, [])
    if len(matches) == 1:
        return matches[0]
    if len(matches) == 0:
        raise FileNotFoundError(f"No WAV found for clip_id={row['clip_id']}")
    raise RuntimeError(f"Multiple WAV files found for clip_id={row['clip_id']}: {matches}")


audio_rows = []
for _, row in manifest_df.iterrows():
    p = resolve_audio_path(row)
    audio_rows.append({'clip_id': str(row['clip_id']), 'ground_truth': str(row['ground_truth']), 'audio_path': str(p)})
audio_df = pd.DataFrame(audio_rows)
print('Selected audio recordings:', len(audio_df))
display(audio_df.head())

Selected audio recordings: 6000

,clip_id,ground_truth,audio_path
0,metro-lisbon-1055-41182,metro,C:\Users\22313906t\Desktop\TAU_project\data_su...
1,shopping_mall-barcelona-125-3702,shopping mall,C:\Users\22313906t\Desktop\TAU_project\data_su...
2,airport-lisbon-1122-41270,airport,C:\Users\22313906t\Desktop\TAU_project\data_su...
3,metro_station-stockholm-239-7087,metro station,C:\Users\22313906t\Desktop\TAU_project\data_su...
4,street_traffic-prague-1193-44472,street traffic,C:\Users\22313906t\Desktop\TAU_project\data_su...

## 5. Load PANNs

In [6]:
print('Loading PANNs...')
panns_model = AudioTagging(checkpoint_path=None, device=PANNS_DEVICE)
print('PANNs loaded.')
print('Number of PANNs labels:', len(labels))

Loading PANNs...
Checkpoint path: C:\Users\22313906t/panns_data/Cnn14_mAP=0.431.pth

C:\Users\22313906t\AppData\Local\anaconda3\envs\tau_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

GPU number: 1
PANNs loaded.
Number of PANNs labels: 527

## 6. Same 3-second chunking as the original notebook

In [7]:
def chunk_audio(y, sr=32000, chunk_seconds=3.0):
    chunk_size = int(sr * chunk_seconds)
    if chunk_size <= 0:
        raise ValueError('chunk_seconds must be > 0')
    chunks = []
    for start_idx in range(0, len(y), chunk_size):
        end_idx = min(start_idx + chunk_size, len(y))
        chunk = y[start_idx:end_idx]
        if len(chunk) == 0:
            continue
        chunks.append({'chunk_index': len(chunks), 'start_s': start_idx / sr, 'end_s': end_idx / sr, 'audio': chunk})
    return chunks

## 7. Same Top-8 PANNs inference per chunk

In [8]:
def classify_panns_chunk(chunk, top_k=8):
    chunk = np.asarray(chunk, dtype=np.float32)
    audio_batch = chunk[np.newaxis, :]
    clipwise_output, embedding = panns_model.inference(audio_batch)
    scores = clipwise_output[0]
    top_indices = np.argsort(scores)[::-1][:top_k]
    predictions = []
    for index in top_indices:
        predictions.append({'label': str(labels[index]), 'score': float(scores[index])})
    return predictions

## 8. Same recording-level aggregation as the original notebook

In [9]:
def classify_panns_audio_file(audio_path, top_k=8, chunk_seconds=3.0, sr=32000):
    audio_path = str(audio_path)
    y, _ = librosa.load(audio_path, sr=sr, mono=True)
    y = np.asarray(y, dtype=np.float32)
    chunks = chunk_audio(y=y, sr=sr, chunk_seconds=chunk_seconds)
    chunk_predictions = []
    for chunk_info in chunks:
        predictions = classify_panns_chunk(chunk=chunk_info['audio'], top_k=top_k)
        chunk_predictions.append({'chunk_index': chunk_info['chunk_index'], 'start_s': chunk_info['start_s'], 'end_s': chunk_info['end_s'], 'labels': predictions})
    label_scores = {}
    for chunk in chunk_predictions:
        for item in chunk['labels']:
            label = item['label']
            score = float(item['score'])
            label_scores.setdefault(label, [])
            label_scores[label].append(score)
    summary = []
    for label, scores in label_scores.items():
        summary.append({'label': label, 'max_score': float(max(scores)), 'mean_score': float(np.mean(scores)), 'count': int(len(scores))})
    summary.sort(key=lambda x: (x['max_score'], x['mean_score'], x['count']), reverse=True)
    return {
        'audio_path': audio_path,
        'num_chunks': len(chunks),
        'chunks': chunk_predictions,
        'summary': summary,
    }

## 9. One-recording test

In [10]:
test_row = audio_df.iloc[0]
test_result = classify_panns_audio_file(
    audio_path=test_row['audio_path'],
    top_k=TOP_K,
    chunk_seconds=CHUNK_SECONDS,
    sr=PANNS_SR,
)
print('Clip:', test_row['clip_id'])
print('Chunks:', test_result['num_chunks'])
display(pd.DataFrame(test_result['summary'][:10]))

Clip: metro-lisbon-1055-41182
Chunks: 4

                           label  max_score  mean_score  count
0                         Speech   0.706648    0.510619      4
1                          Train   0.597942    0.425186      4
2                        Vehicle   0.523056    0.479815      4
3                 Rail transport   0.436387    0.266602      4
4      Railroad car, train wagon   0.403455    0.230627      4
5     Subway, metro, underground   0.267064    0.176796      3
6                Field recording   0.149755    0.112956      2
7                       Aircraft   0.093867    0.082256      2
8                          Music   0.084393    0.084393      1
9  Fixed-wing aircraft, airplane   0.078666    0.078666      1

## 10. Fresh run or resume

Set `FRESH_RUN = True` only when you intentionally want to delete old 6000
PANNs outputs and rerun from zero. Otherwise leave it `False`.

In [11]:
FRESH_RUN = False
if FRESH_RUN:
    for path in [ALL_EVENTS_PATH, ALL_TOP_PATH, ALL_ERRORS_PATH]:
        if path.exists():
            path.unlink()
            print('Deleted:', path)
    print('Fresh PANNs run ready.')
else:
    print('Resume mode: existing outputs will be kept.')

Resume mode: existing outputs will be kept.

## 11. Resume/checkpoint setup

In [12]:
if ALL_EVENTS_PATH.exists():
    existing_events_df = pd.read_csv(ALL_EVENTS_PATH)
else:
    existing_events_df = pd.DataFrame()
if ALL_TOP_PATH.exists():
    existing_top_df = pd.read_csv(ALL_TOP_PATH)
    processed_ids = set(existing_top_df['clip_id'].astype(str))
else:
    existing_top_df = pd.DataFrame()
    processed_ids = set()
if ALL_ERRORS_PATH.exists():
    existing_errors_df = pd.read_csv(ALL_ERRORS_PATH)
else:
    existing_errors_df = pd.DataFrame()
remaining_df = audio_df[~audio_df['clip_id'].astype(str).isin(processed_ids)].copy().reset_index(drop=True)
print('Total clips:', len(audio_df))
print('Already processed:', len(processed_ids))
print('Remaining:', len(remaining_df))

Total clips: 6000
Already processed: 0
Remaining: 6000

In [13]:
new_event_rows = []
new_top_rows = []
new_error_rows = []


def save_panns_checkpoint():
    global existing_events_df
    global existing_top_df
    global existing_errors_df
    global new_event_rows
    global new_top_rows
    global new_error_rows
    if new_event_rows:
        temp = pd.DataFrame(new_event_rows)
        existing_events_df = pd.concat([existing_events_df, temp], ignore_index=True)
        existing_events_df = existing_events_df.drop_duplicates(subset=['clip_id', 'label'], keep='last')
        existing_events_df.to_csv(ALL_EVENTS_PATH, index=False)
        new_event_rows = []
    if new_top_rows:
        temp = pd.DataFrame(new_top_rows)
        existing_top_df = pd.concat([existing_top_df, temp], ignore_index=True)
        existing_top_df = existing_top_df.drop_duplicates(subset=['clip_id'], keep='last')
        existing_top_df.to_csv(ALL_TOP_PATH, index=False)
        new_top_rows = []
    if new_error_rows:
        temp = pd.DataFrame(new_error_rows)
        existing_errors_df = pd.concat([existing_errors_df, temp], ignore_index=True)
        existing_errors_df = existing_errors_df.drop_duplicates(subset=['clip_id'], keep='last')
        existing_errors_df.to_csv(ALL_ERRORS_PATH, index=False)
        new_error_rows = []

## 12. Run PANNs on the 6000 development recordings

In [14]:
processed_since_checkpoint = 0
start_time = time.time()
total_remaining = len(remaining_df)
for idx, row in remaining_df.iterrows():
    clip_id = str(row['clip_id'])
    ground_truth = str(row['ground_truth'])
    current_audio_path = str(row['audio_path'])
    print(f'[{idx + 1}/{total_remaining}] {ground_truth:20s} | {clip_id}')
    try:
        result = classify_panns_audio_file(
            audio_path=current_audio_path,
            top_k=TOP_K,
            chunk_seconds=CHUNK_SECONDS,
            sr=PANNS_SR,
        )
        for event in result['summary']:
            new_event_rows.append({'clip_id': clip_id, 'ground_truth': ground_truth, 'label': event['label'], 'max_score': event['max_score'], 'mean_score': event['mean_score'], 'count': event['count'], 'num_chunks': result['num_chunks']})
        top_row = {'clip_id': clip_id, 'ground_truth': ground_truth, 'num_chunks': result['num_chunks']}
        for rank, event in enumerate(result['summary'][:10], start=1):
            top_row[f'event_{rank}'] = event['label']
            top_row[f'score_{rank}'] = event['max_score']
        new_top_rows.append(top_row)
    except Exception as e:
        print('ERROR:', clip_id, str(e))
        new_error_rows.append({'clip_id': clip_id, 'ground_truth': ground_truth, 'audio_path': current_audio_path, 'error': str(e)})
    processed_since_checkpoint += 1
    if processed_since_checkpoint >= CHECKPOINT_EVERY:
        save_panns_checkpoint()
        processed_since_checkpoint = 0
        print('----- PANNs CHECKPOINT SAVED -----')
save_panns_checkpoint()
elapsed_minutes = (time.time() - start_time) / 60
print('\nPANNs processing complete.')
print('Elapsed minutes:', round(elapsed_minutes, 2))
print('\nEvents:', ALL_EVENTS_PATH)
print('Top events:', ALL_TOP_PATH)
if ALL_ERRORS_PATH.exists():
    print('Errors:', ALL_ERRORS_PATH)

[1/6000] metro                | metro-lisbon-1055-41182
[2/6000] shopping mall        | shopping_mall-barcelona-125-3702
[3/6000] airport              | airport-lisbon-1122-41270
[4/6000] metro station        | metro_station-stockholm-239-7087
[5/6000] street traffic       | street_traffic-prague-1193-44472
[6/6000] bus                  | bus-lyon-1124-41154
[7/6000] bus                  | bus-helsinki-19-776
[8/6000] airport              | airport-lisbon-1175-44703
[9/6000] metro                | metro-lyon-1206-44910
[10/6000] airport              | airport-london-205-6192
[11/6000] street traffic       | street_traffic-london-270-8216
[12/6000] park                 | park-lyon-1188-44569
[13/6000] bus                  | bus-lisbon-1212-45534
[14/6000] airport              | airport-paris-7-345
[15/6000] public square        | public_square-lyon-1017-41596
[16/6000] park                 | park-lisbon-1057-42931
[17/6000] metro station        | metro_station-barcelona-229-6893
[18/6000] street traffic       | street_traffic-lyon-1045-44087
[19/6000] airport              | airport-milan-1089-41269
[20/6000] airport              | airport-lisbon-1114-43068
[21/6000] bus                  | bus-barcelona-210-6417
[22/6000] tram                 | tram-milan-1134-41334
[23/6000] shopping mall        | shopping_mall-lyon-1066-42368
[24/6000] park                 | park-lyon-1144-42608
[25/6000] street traffic       | street_traffic-vienna-177-5476
----- PANNs CHECKPOINT SAVED -----
[26/6000] shopping mall        | shopping_mall-stockholm-135-4089
[27/6000] metro station        | metro_station-helsinki-65-1956
[28/6000] tram                 | tram-prague-1088-40537
[29/6000] public square        | public_square-lyon-1056-43050
[30/6000] shopping mall        | shopping_mall-london-256-7713
[31/6000] tram                 | tram-lyon-1103-42890
[32/6000] street traffic       | street_traffic-london-169-5186
[33/6000] shopping mall        | shopping_mall-lisbon-1002-41783
[34/6000] metro                | metro-lisbon-1217-44291
[35/6000] metro station        | metro_station-helsinki-66-1973
[36/6000] airport              | airport-stockholm-11-455
[37/6000] shopping mall        | shopping_mall-lisbon-1002-40900
[38/6000] park                 | park-lisbon-1057-41926
[39/6000] tram                 | tram-lisbon-1200-45720
[40/6000] park                 | park-stockholm-102-2889
[41/6000] park                 | park-barcelona-90-2476
[42/6000] bus                  | bus-barcelona-17-703
[43/6000] airport              | airport-lisbon-1000-44083
[44/6000] public square        | public_square-london-250-7487
[45/6000] street traffic       | street_traffic-milan-1094-43637
[46/6000] shopping mall        | shopping_mall-prague-1009-43304
[47/6000] tram                 | tram-lyon-1112-43348
[48/6000] shopping mall        | shopping_mall-barcelona-125-3730
[49/6000] metro                | metro-prague-1163-44734
[50/6000] airport              | airport-london-5-229
----- PANNs CHECKPOINT SAVED -----
[51/6000] bus                  | bus-helsinki-211-6439
[52/6000] bus                  | bus-milan-1154-42163
[53/6000] bus                  | bus-vienna-40-1185
[54/6000] public square        | public_square-prague-1111-41011
[55/6000] public square        | public_square-paris-116-3385
[56/6000] pedestrian street    | street_pedestrian-lyon-1072-43350
[57/6000] public square        | public_square-barcelona-107-3061
[58/6000] shopping mall        | shopping_mall-vienna-140-4255
[59/6000] bus                  | bus-prague-1032-43822
[60/6000] street traffic       | street_traffic-prague-1006-43649
[61/6000] shopping mall        | shopping_mall-stockholm-136-4110
[62/6000] metro station        | metro_station-lisbon-1020-42626
[63/6000] tram                 | tram-helsinki-184-5714
[64/6000] pedestrian street    | street_pedestrian-lyon-1003-41906
[65/6000] metro                | metro-helsinki-222-6715
[66/6000] public square        | public_square-london-114-3334
[67/6000] public square        | public_square-lyon-1024-41785
[68/6000] public square        | public_square-prague-1214-44770
[69/6000] metro                | metro-vienna-58-1743
[70/6000] airport              | airport-milan-1172-44126
[71/6000] public square        | public_square-vienna-124-3672
[72/6000] pedestrian street    | street_pedestrian-lisbon-1099-40538
[73/6000] park                 | park-prague-1092-43435
[74/6000] metro station        | metro_station-lisbon-1221-45644
[75/6000] shopping mall        | shopping_mall-vienna-139-4234
----- PANNs CHECKPOINT SAVED -----
[76/6000] metro                | metro-stockholm-55-1617
[77/6000] airport              | airport-milan-1108-43486
[78/6000] airport              | airport-stockholm-12-506
[79/6000] metro station        | metro_station-prague-1118-42884
[80/6000] airport              | airport-lyon-1095-43330
[81/6000] pedestrian street    | street_pedestrian-london-150-4534
[82/6000] pedestrian street    | street_pedestrian-lyon-1162-45371
[83/6000] pedestrian street    | street_pedestrian-paris-153-4632
[84/6000] airport              | airport-lisbon-1122-40888
[85/6000] airport              | airport-london-6-274
[86/6000] street traffic       | street_traffic-lyon-1029-40501
[87/6000] airport              | airport-stockholm-11-456
[88/6000] shopping mall        | shopping_mall-london-256-7685
[89/6000] public square        | public_square-paris-118-3454
[90/6000] park                 | park-lisbon-1198-45557
[91/6000] park                 | park-stockholm-246-7343
[92/6000] metro station        | metro_station-milan-1117-43845
[93/6000] tram                 | tram-helsinki-184-5713
[94/6000] airport              | airport-prague-1034-43238
[95/6000] bus                  | bus-vienna-219-6616
[96/6000] shopping mall        | shopping_mall-helsinki-255-7645
[97/6000] metro                | metro-stockholm-56-1654
[98/6000] metro                | metro-lyon-1206-44713
[99/6000] bus                  | bus-barcelona-16-643
[100/6000] airport              | airport-lyon-1041-41216
----- PANNs CHECKPOINT SAVED -----
[101/6000] park                 | park-london-243-7229
[102/6000] metro station        | metro_station-prague-1170-44911
[103/6000] street traffic       | street_traffic-stockholm-175-5391
[104/6000] public square        | public_square-lisbon-1039-43154
[105/6000] bus                  | bus-milan-1083-40287
[106/6000] pedestrian street    | street_pedestrian-lyon-1003-42656
[107/6000] metro station        | metro_station-lisbon-1021-42906
[108/6000] public square        | public_square-paris-251-7532
[109/6000] bus                  | bus-vienna-39-1177
[110/6000] metro station        | metro_station-barcelona-229-6892
[111/6000] park                 | park-lisbon-1057-43446
[112/6000] tram                 | tram-stockholm-284-8593
[113/6000] park                 | park-lisbon-1057-41445
[114/6000] public square        | public_square-stockholm-119-3510
[115/6000] airport              | airport-stockholm-208-6342
[116/6000] metro station        | metro_station-prague-1019-42458
[117/6000] airport              | airport-lyon-1169-44981
[118/6000] bus                  | bus-lyon-1159-40908
[119/6000] metro                | metro-prague-1026-43278
[120/6000] metro station        | metro_station-helsinki-65-1964
[121/6000] public square        | public_square-vienna-253-7601
[122/6000] metro                | metro-lisbon-1224-45308
[123/6000] shopping mall        | shopping_mall-helsinki-130-3900
[124/6000] shopping mall        | shopping_mall-lyon-1043-41875
[125/6000] shopping mall        | shopping_mall-lisbon-1125-43904
----- PANNs CHECKPOINT SAVED -----
[126/6000] tram                 | tram-prague-1161-43748
[127/6000] public square        | public_square-lyon-1024-43928
[128/6000] bus                  | bus-prague-1102-40498
[129/6000] street traffic       | street_traffic-london-169-5167
[130/6000] metro                | metro-prague-1054-42720
[131/6000] pedestrian street    | street_pedestrian-paris-265-8056
[132/6000] street traffic       | street_traffic-london-168-5152
[133/6000] public square        | public_square-london-115-3345
[134/6000] pedestrian street    | street_pedestrian-stockholm-156-4749
[135/6000] metro                | metro-vienna-59-1787
[136/6000] public square        | public_square-milan-1044-43909
[137/6000] public square        | public_square-barcelona-248-7413
[138/6000] airport              | airport-lyon-1095-44085
[139/6000] airport              | airport-lisbon-1000-41194
[140/6000] metro                | metro-milan-1141-40656
[141/6000] park                 | park-london-243-7256
[142/6000] airport              | airport-lyon-1041-40530
[143/6000] public square        | public_square-london-250-7484
[144/6000] tram                 | tram-lisbon-1100-43477
[145/6000] metro station        | metro_station-helsinki-67-2000
[146/6000] airport              | airport-lisbon-1175-44916
[147/6000] metro station        | metro_station-lyon-1179-44301
[148/6000] metro station        | metro_station-stockholm-84-2265
[149/6000] bus                  | bus-lisbon-1013-42545
[150/6000] pedestrian street    | street_pedestrian-barcelona-261-7922
----- PANNs CHECKPOINT SAVED -----
[151/6000] park                 | park-lisbon-1198-45531
[152/6000] tram                 | tram-milan-1065-42123
[153/6000] bus                  | bus-lisbon-1013-40015
[154/6000] metro                | metro-lisbon-1121-42856
[155/6000] pedestrian street    | street_pedestrian-helsinki-262-7929
[156/6000] metro station        | metro_station-lisbon-1020-41510
[157/6000] bus                  | bus-vienna-219-6619
[158/6000] pedestrian street    | street_pedestrian-prague-1085-43483
[159/6000] airport              | airport-milan-1061-40638
[160/6000] metro                | metro-stockholm-56-1669
[161/6000] public square        | public_square-paris-118-3467
[162/6000] metro                | metro-vienna-59-1758
[163/6000] airport              | airport-lisbon-1175-44864
[164/6000] park                 | park-lyon-1188-45633
[165/6000] tram                 | tram-prague-1184-45368
[166/6000] street traffic       | street_traffic-milan-1097-42537
[167/6000] metro                | metro-lyon-1126-43128
[168/6000] airport              | airport-lyon-1169-44738
[169/6000] shopping mall        | shopping_mall-stockholm-137-4141
[170/6000] shopping mall        | shopping_mall-prague-1219-44685
[171/6000] airport              | airport-milan-1089-40910
[172/6000] bus                  | bus-barcelona-17-680
[173/6000] airport              | airport-london-6-289
[174/6000] shopping mall        | shopping_mall-stockholm-258-7819
[175/6000] tram                 | tram-prague-1088-41430
----- PANNs CHECKPOINT SAVED -----
[176/6000] street traffic       | street_traffic-helsinki-164-5023
[177/6000] pedestrian street    | street_pedestrian-london-149-4528
[178/6000] tram                 | tram-prague-1071-42010
[179/6000] metro station        | metro_station-stockholm-84-2252
[180/6000] tram                 | tram-helsinki-182-5656
[181/6000] bus                  | bus-milan-1078-40649
[182/6000] street traffic       | street_traffic-vienna-274-8370
[183/6000] street traffic       | street_traffic-prague-1153-41532
[184/6000] shopping mall        | shopping_mall-lisbon-1176-45590
[185/6000] street traffic       | street_traffic-lyon-1110-43260
[186/6000] park                 | park-stockholm-245-7307
[187/6000] shopping mall        | shopping_mall-lyon-1066-41463
[188/6000] metro station        | metro_station-london-76-2107
[189/6000] public square        | public_square-stockholm-119-3503
[190/6000] metro                | metro-lyon-1206-44953
[191/6000] bus                  | bus-helsinki-19-759
[192/6000] shopping mall        | shopping_mall-lisbon-1125-43490
[193/6000] metro station        | metro_station-milan-1187-44597
[194/6000] street traffic       | street_traffic-vienna-177-5447
[195/6000] park                 | park-barcelona-91-2502
[196/6000] bus                  | bus-milan-1115-42917
[197/6000] tram                 | tram-lyon-1150-41055
[198/6000] street traffic       | street_traffic-lyon-1045-40180
[199/6000] shopping mall        | shopping_mall-prague-1219-44761
[200/6000] metro                | metro-milan-1062-42749
----- PANNs CHECKPOINT SAVED -----
[201/6000] park                 | park-lyon-1188-44277
[202/6000] street traffic       | street_traffic-lyon-1029-41758
[203/6000] public square        | public_square-london-114-3319
[204/6000] street traffic       | street_traffic-barcelona-268-8166
[205/6000] park                 | park-paris-100-2838
[206/6000] street traffic       | street_traffic-lyon-1045-43864
[207/6000] pedestrian street    | street_pedestrian-lisbon-1004-41802
[208/6000] bus                  | bus-milan-1154-42127
[209/6000] shopping mall        | shopping_mall-prague-1219-44349
[210/6000] bus                  | bus-barcelona-210-6415
[211/6000] pedestrian street    | street_pedestrian-milan-1080-43769
[212/6000] airport              | airport-stockholm-11-452
[213/6000] bus                  | bus-milan-1180-45242
[214/6000] metro station        | metro_station-stockholm-84-2279
[215/6000] shopping mall        | shopping_mall-stockholm-135-4101
[216/6000] park                 | park-lyon-1188-44323
[217/6000] metro station        | metro_station-london-68-2020
[218/6000] pedestrian street    | street_pedestrian-lisbon-1099-42250
[219/6000] pedestrian street    | street_pedestrian-helsinki-146-4409
[220/6000] public square        | public_square-prague-1111-40400
[221/6000] tram                 | tram-helsinki-184-5745
[222/6000] bus                  | bus-helsinki-211-6434
[223/6000] tram                 | tram-prague-1109-41241
[224/6000] shopping mall        | shopping_mall-helsinki-128-3818
[225/6000] park                 | park-lisbon-1104-43999
----- PANNs CHECKPOINT SAVED -----
[226/6000] park                 | park-barcelona-90-2465
[227/6000] metro                | metro-vienna-58-1738
[228/6000] shopping mall        | shopping_mall-prague-1053-44045
[229/6000] park                 | park-lyon-1012-43206
[230/6000] airport              | airport-london-205-6219
[231/6000] metro                | metro-vienna-59-1755
[232/6000] metro station        | metro_station-lyon-1077-40844
[233/6000] shopping mall        | shopping_mall-vienna-259-7878
[234/6000] shopping mall        | shopping_mall-prague-1009-40072
[235/6000] bus                  | bus-vienna-38-1123
[236/6000] shopping mall        | shopping_mall-barcelona-126-3764
[237/6000] metro                | metro-lisbon-1224-44955
[238/6000] public square        | public_square-helsinki-112-3256
[239/6000] shopping mall        | shopping_mall-milan-1084-41849
[240/6000] street traffic       | street_traffic-lyon-1045-40062
[241/6000] pedestrian street    | street_pedestrian-lisbon-1004-43569
[242/6000] airport              | airport-lisbon-1122-43787
[243/6000] park                 | park-lyon-1144-42082
[244/6000] airport              | airport-prague-1195-45096
[245/6000] street traffic       | street_traffic-vienna-178-5490
[246/6000] shopping mall        | shopping_mall-prague-1219-45542
[247/6000] airport              | airport-london-6-282
[248/6000] park                 | park-prague-1092-44052
[249/6000] shopping mall        | shopping_mall-lisbon-1125-40521
[250/6000] metro station        | metro_station-prague-1130-40768
----- PANNs CHECKPOINT SAVED -----
[251/6000] park                 | park-paris-100-2841
[252/6000] tram                 | tram-stockholm-198-5958
[253/6000] metro station        | metro_station-lisbon-1007-41848
[254/6000] bus                  | bus-lyon-1177-45193
[255/6000] bus                  | bus-lyon-1186-45061
[256/6000] street traffic       | street_traffic-london-168-5148
[257/6000] airport              | airport-milan-1061-40886
[258/6000] metro                | metro-prague-1016-40651
[259/6000] street traffic       | street_traffic-vienna-177-5464
[260/6000] bus                  | bus-vienna-38-1130
[261/6000] metro                | metro-vienna-59-1753
[262/6000] metro                | metro-stockholm-56-1663
[263/6000] bus                  | bus-lisbon-1070-42589
[264/6000] airport              | airport-milan-1108-41898
[265/6000] airport              | airport-lisbon-1000-41312
[266/6000] park                 | park-barcelona-90-2494
[267/6000] tram                 | tram-lyon-1103-43552
[268/6000] pedestrian street    | street_pedestrian-barcelona-143-4327
[269/6000] pedestrian street    | street_pedestrian-vienna-159-4848
[270/6000] tram                 | tram-prague-1071-40488
[271/6000] airport              | airport-prague-1015-41221
[272/6000] park                 | park-stockholm-245-7305
[273/6000] tram                 | tram-stockholm-199-5993
[274/6000] pedestrian street    | street_pedestrian-stockholm-266-8074
[275/6000] airport              | airport-lyon-1095-43774
----- PANNs CHECKPOINT SAVED -----
[276/6000] metro                | metro-lyon-1079-43199
[277/6000] street traffic       | street_traffic-milan-1011-43086
[278/6000] bus                  | bus-barcelona-16-654
[279/6000] tram                 | tram-helsinki-183-5709
[280/6000] airport              | airport-lyon-1095-43055
[281/6000] shopping mall        | shopping_mall-milan-1084-40740
[282/6000] metro                | metro-prague-1081-43969
[283/6000] metro station        | metro_station-prague-1019-40721
[284/6000] metro                | metro-helsinki-45-1367
[285/6000] park                 | park-prague-1185-44287
[286/6000] bus                  | bus-prague-1194-45091
[287/6000] bus                  | bus-vienna-40-1198
[288/6000] pedestrian street    | street_pedestrian-stockholm-155-4713
[289/6000] street traffic       | street_traffic-lyon-1029-42465
[290/6000] shopping mall        | shopping_mall-london-256-7737
[291/6000] pedestrian street    | street_pedestrian-prague-1085-42780
[292/6000] pedestrian street    | street_pedestrian-prague-1085-41265
[293/6000] bus                  | bus-lisbon-1223-44429
[294/6000] bus                  | bus-prague-1215-45746
[295/6000] public square        | public_square-helsinki-112-3254
[296/6000] tram                 | tram-vienna-200-6031
[297/6000] street traffic       | street_traffic-lyon-1045-42929
[298/6000] bus                  | bus-stockholm-34-1040
[299/6000] street traffic       | street_traffic-paris-171-5239
[300/6000] park                 | park-paris-100-2849
----- PANNs CHECKPOINT SAVED -----
[301/6000] metro                | metro-lyon-1181-44862
[302/6000] metro                | metro-lyon-1139-40766
[303/6000] tram                 | tram-stockholm-197-5952
[304/6000] airport              | airport-paris-206-6244
[305/6000] tram                 | tram-prague-1184-44119
[306/6000] park                 | park-helsinki-94-2637
[307/6000] tram                 | tram-helsinki-276-8427
[308/6000] park                 | park-stockholm-101-2866
[309/6000] tram                 | tram-helsinki-183-5697
[310/6000] metro                | metro-vienna-60-1804
[311/6000] public square        | public_square-lisbon-1039-40103
[312/6000] metro station        | metro_station-prague-1118-41075
[313/6000] metro                | metro-barcelona-220-6647
[314/6000] airport              | airport-lyon-1169-44430
[315/6000] street traffic       | street_traffic-london-168-5146
[316/6000] bus                  | bus-milan-1155-43187
[317/6000] airport              | airport-london-6-291
[318/6000] metro                | metro-vienna-58-1725
[319/6000] park                 | park-vienna-105-3000
[320/6000] metro                | metro-vienna-59-1754
[321/6000] metro                | metro-vienna-58-1720
[322/6000] tram                 | tram-helsinki-182-5665
[323/6000] bus                  | bus-barcelona-16-660

## 13. Add persistence and inspect final output

In [15]:
all_panns_events_df = pd.read_csv(ALL_EVENTS_PATH)
all_panns_top_df = pd.read_csv(ALL_TOP_PATH)
all_panns_events_df[
    'persistence'] = pd.to_numeric(all_panns_events_df['count'],
    errors='coerce') / pd.to_numeric(all_panns_events_df['num_chunks'],
    errors='coerce').replace(0,
    np.nan,
)

# Save persistence in the canonical 6000 event file as a convenience.
all_panns_events_df.to_csv(ALL_EVENTS_PATH, index=False)
print('Processed clips:', all_panns_top_df['clip_id'].astype(str).nunique())
print('PANNs event rows:', len(all_panns_events_df))
display(all_panns_events_df.head(20))

Processed clips: 6000
PANNs event rows: 86665

,clip_id,ground_truth,label,max_score,mean_score,count,num_chunks,persistence
0,metro-lisbon-1055-41182,metro,Speech,0.706648,0.510619,4,4,1.00
1,metro-lisbon-1055-41182,metro,Train,0.597942,0.425186,4,4,1.00
2,metro-lisbon-1055-41182,metro,Vehicle,0.523056,0.479815,4,4,1.00
3,metro-lisbon-1055-41182,metro,Rail transport,0.436387,0.266602,4,4,1.00
4,metro-lisbon-1055-41182,metro,"Railroad car, train wagon",0.403455,0.230627,4,4,1.00
5,metro-lisbon-1055-41182,metro,"Subway, metro, underground",0.267064,0.176796,3,4,0.75
6,metro-lisbon-1055-41182,metro,Field recording,0.149755,0.112956,2,4,0.50
7,metro-lisbon-1055-41182,metro,Aircraft,0.093867,0.082256,2,4,0.50
8,metro-lisbon-1055-41182,metro,Music,0.084393,0.084393,1,4,0.25
9,metro-lisbon-1055-41182,metro,"Fixed-wing aircraft, airplane",0.078666,0.078666,1,4,0.25
10,metro-lisbon-1055-41182,metro,Train wheels squealing,0.075085,0.075085,1,4,0.25
11,metro-lisbon-1055-41182,metro,"Outside, urban or manmade",0.062906,0.062906,1,4,0.25
12,metro-lisbon-1055-41182,metro,Bus,0.047282,0.047282,1,4,0.25
13,shopping_mall-barcelona-125-3702,shopping mall,Speech,0.735571,0.533189,4,4,1.00
14,shopping_mall-barcelona-125-3702,shopping mall,Music,0.711672,0.466848,4,4,1.00
15,shopping_mall-barcelona-125-3702,shopping mall,Animal,0.083485,0.047348,4,4,1.00
16,shopping_mall-barcelona-125-3702,shopping mall,"Inside, public space",0.057811,0.050997,2,4,0.50
17,shopping_mall-barcelona-125-3702,shopping mall,Vehicle,0.055189,0.043311,4,4,1.00
18,shopping_mall-barcelona-125-3702,shopping mall,Clip-clop,0.046833,0.046833,1,4,0.25
19,shopping_mall-barcelona-125-3702,shopping mall,Chatter,0.045099,0.043983,2,4,0.50